version: '3.8'
services:
  binar10_back:
    container_name: binar10_back
    build: ./
    restart: always
    depends_on:
      - postgres_db
      - mongo_db
    env_file:
      - docker.env
    ports:
      - "5000:5000"
  postgres_db:
    container_name: postgres_db
    image: postgres
    ports:
      - "4561:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Bv{-jqW{&L23dMkJ5N"
      POSTGRES_DB: "binar10_db"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
  mongo_db:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "Bv{-jqW{&L23d$JF)"
